project:
  type: website
  output-dir: '.'
website:
  title: "BYUI-Timeseries-Drafts"
  page-navigation: true
  navbar:
      background: primary
      left:
        - text: "Home"
          file: index.qmd
        - text: "Tutorials"
          menu:
            - text: "Cheatsheets"
              file: Tutorials/tutorials.qmd
            - text: "Rstudio"
              file: Tutorials/tutorial_1.qmd
            - text: "Github"
              file: Tutorials/tutorial_2.qmd
            - text: "Templates"
              file: Tutorials/templates.qmd
        - text: "Chapter 1"
          file: chapter_1/Chapter_1.qmd
        - text: "Chapter 2"
          file: chapter_2/Chapter_2.qmd
        - text: "Chapter 3"
          file: chapter_3/Chapter_3.qmd
        - text: "Chapter 4"
          file: chapter_4/Chapter_4.qmd

  sidebar:
    - title: "Tutorials"
      style: "docked"
      contents:
        - Tutorials/tutorials.qmd
        - Tutorials/tutorial_1.qmd
        - Tutorials/tutorial_2.qmd
        - Tutorials/templates.qmd

    - title: "Chapter 1"
      contents:
        - chapter_1/Chapter_1.qmd
        - section: "Time Series Introduction"
          contents:
            - chapter_1/chapter_1_lesson_1_class.qmd
        - section: "Plots, Trends, and Seasonal Variation"
          contents:
            - chapter_1/chapter_1_lesson_2_class.qmd
        - section: "Averages for Time Series"
          contents:
            - chapter_1/chapter_1_lesson_3_class.qmd
        - section: "Decomposition of Time Series"
          contents:
            - chapter_1/chapter_1_lesson_4_class.qmd

    - title: "Chapter 2"
      contents:
        - chapter_2/Chapter_2.qmd
        - section: "Expectation & Ensemble"
          contents:
            - chapter_2/chapter_2_lesson_1_class.qmd
        - section: "Autocorrelation"
          contents:
            - chapter_2/chapter_2_lesson_2_class.qmd
        - section: "Correlograms & Covariance of Sums"
          contents:
            - chapter_2/chapter_2_lesson_3_class.qmd

    - title: "Chapter 3"
      contents:
        - chapter_3/Chapter_3.qmd
        - section: "Leading variables & associated variables"
          contents:
            - chapter_3/chapter_3_lesson_1_class.qmd
        # - section: "Exponential smoothing"
        #   contents:
        #     - chapter_3/Chapter_3_2.qmd

    # - title: "Chapter 4"
    #   contents:
    #     - chapter_4/Chapter_4.qmd
    #     - section: "White noise & Random walks"
    #       contents:
    #         - chapter_4/Chapter_4_lesson_1_class.qmd
    #     - section: "Fitted models and diagnostic plots"
    #       contents:
    #         - chapter_4/Chapter_4_2.qmd
    #         - chapter_4/Chapter_4_2_CA.qmd
    #     - section: "Autoregressive models"
    #       contents:
    #         - chapter_4/Chapter_4_3.qmd
    #         - chapter_4/Chapter_4_3_CA.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual


