project:
  type: website
  output-dir: content
website:
  title: "BYUI-Timeseries-Drafts"
  favicon: favicon.png
  page-navigation: true
  navbar:
      background: primary
      logo: images/favicon.png
      left:
        - text: "Table of Contents"
          file: index.qmd
        - sidebar:resources
        - sidebar:chapter_1
        - sidebar:chapter_2
        - sidebar:chapter_3
        # - sidebar:chapter_4
        # - sidebar:chapter_5
        # - sidebar:chapter_6

  sidebar:
    - id: resources
      title: "Resources"
      style: "docked"
      collapse-level: 1
      contents:
        - section: "Table of Contents"
          contents:
            - resources/tutorials.qmd
        - section: "Lesson 1"
          contents:
            - resources/tutorial_1.qmd
        - section: "Lesson 2"
          contents:
            - resources/tutorial_2.qmd

    - id: chapter_1
      title: "Chapter 1"
      style: "docked"
      collapse-level: 1
      contents:
        - section: "Table of Contents"
          contents:
            - chapter_1.qmd
        - section: "Lesson 1"
          contents:
            - chapter_1_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_1_lesson_2.qmd
        - section: "Lesson 3"
          contents:
            - chapter_1_lesson_3.qmd
        - section: "Lesson 4"
          contents:
            - chapter_1_lesson_4.qmd

    - id: chapter_2
      title: "Chapter 2"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Table of Contents"
          contents:
            - chapter_2.qmd
        - section: "Lesson 1"
          contents:
            - chapter_2_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_2_lesson_2.qmd
        - section: "Lesson 3"
          contents:
            - chapter_2_lesson_3.qmd

    - id: chapter_3
      title: "Chapter 3"
      style: "docked"
      collapse-level: 2
      contents:
#        - auto: "*_3.qmd" # if we redid the naming scheme like below we could use auto population methods
#        - chapter_3/lesson_1_chapter_3.qmd
        - section: "Table of Contents"
          contents:
            - chapter_3.qmd
        - section: "Lesson 1"
          contents:
            - chapter_3_lesson_1.qmd
        - section: "Lesson 2"
          contents:
            - chapter_3_lesson_2.qmd
        - section: "Lesson 3"
          contents:
            - chapter_3_lesson_3.qmd
#
#     - id: chapter_4
#       title: "Chapter 4"
#       style: "docked"
#       collapse-level: 2
#       contents:
#         - section: "Table of Contents"
#           contents:
#             - chapter_4.qmd
#         - section: "Lesson 1"
#           contents:
#             - chapter_4_lesson_1.qmd
#         - section: "Lesson 2"
#           contents:
#             - chapter_4_lesson_2.qmd
#         - section: "Lesson 3"
#           contents:
#             - chapter_4_lesson_3.qmd
#
#     - id: chapter_5
#       title: "Chapter 5"
#       style: "docked"
#       collapse-level: 2
#       contents:
#         - section: "Table of Contents"
#           contents:
#             - chapter_5.qmd
#         - section: "Lesson 1"
#           contents:
#             - chapter_5_lesson_1.qmd
#         - section: "Lesson 2"
#           contents:
#             - chapter_5_lesson_2.qmd
#         - section: "Lesson 3"
#           contents:
#             - chapter_5_lesson_3.qmd
#
#     - id: chapter_6
#       title: "Chapter 6"
#       style: "docked"
#       collapse-level: 2
#       contents:
#         - section: "Table of Contents"
#           contents:
#             - chapter_6.qmd
#         - section: "Lesson 1"
#           contents:
#             - chapter_6_lesson_1.qmd
#         - section: "Lesson 2"
#           contents:
#             - chapter_6_lesson_2.qmd
#         - section: "Lesson 3"
#           contents:
#             - chapter_6_lesson_3.qmd

format:
  html:
    theme:
      light: [cosmo, theme-byui.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: source


