project:
  type: website
  output-dir: '.'
website:
  title: "BYUI-Timeseries-Drafts"
  page-navigation: true
  navbar:
      background: primary
      left:
        - text: "Home"
          file: index.qmd
        - text: "Tutorials"
          menu:
            - text: "Cheatsheets"
              file: Tutorials/tutorials.qmd
            - text: "Rstudio"
              file: Tutorials/tutorial_1.qmd
            - text: "Github"
              file: Tutorials/tutorial_2.qmd
            - text: "Templates"
              file: Tutorials/templates.qmd
        - sidebar:chapter_1
        - sidebar:chapter_2
        - sidebar:chapter_3
        - sidebar:chapter_4
        - sidebar:chapter_5
        - sidebar:chapter_6

  sidebar:
    - title: "Tutorials"
      contents:
        - Tutorials/tutorials.qmd
        - Tutorials/tutorial_1.qmd
        - Tutorials/tutorial_2.qmd
        - Tutorials/templates.qmd
    - id: chapter_1
      title: "Chapter 1"
      style: "docked"
      collapse-level: 1
      contents:
        - section: "Table of Contents"
          contents:
            - chapter_1/chapter_1.qmd
        - section: "Lesson 1"
          contents:
            - chapter_1/chapter_1_lesson_1_class.qmd
        - section: "Lesson 2"
          contents:
            - chapter_1/chapter_1_lesson_2_class.qmd
        - section: "Lesson 3"
          contents:
            - chapter_1/chapter_1_lesson_3_class.qmd
        - section: "Lesson 4"
          contents:
            - chapter_1/chapter_1_lesson_4_class.qmd

    - id: chapter_2
      title: "Chapter 2"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Expectation & Ensemble"
          contents:
            - chapter_2/chapter_2_lesson_1_class.qmd
        - section: "Autocorrelation"
          contents:
            - chapter_2/chapter_2_lesson_2_class.qmd
        - section: "Correlograms & Covariance of Sums"
          contents:
            - chapter_2/chapter_2_lesson_3_class.qmd

    - id: chapter_3
      title: "Chapter 3"
      style: "docked"
      collapse-level: 2
      contents:
#        - auto: "*_3_class.qmd"
#        - chapter_3/lesson_1_chapter_3_class.qmd
        - section: "Lesson 1"
          contents:
            - chapter_3/chapter_3_lesson_1_class.qmd
        - section: "Lesson 2"
          contents:
            - chapter_3/chapter_3_lesson_2_class.qmd
        - section: "Lesson 3"
          contents:
            - chapter_3/chapter_3_lesson_3_class.qmd
        - section: "Lesson 4"
          contents:
            - chapter_3/chapter_3_lesson_4_class.qmd

    - id: chapter_4
      title: "Chapter 4"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Expectation & Ensemble"
          contents:
            - chapter_4/chapter_4_lesson_1_class.qmd
        - section: "Autocorrelation"
          contents:
            - chapter_4/chapter_4_lesson_2_class.qmd
        - section: "Correlograms & Covariance of Sums"
          contents:
            - chapter_4/chapter_4_lesson_3_class.qmd

    - id: chapter_5
      title: "Chapter 5"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Expectation & Ensemble"
          contents:
            - chapter_5/chapter_5_lesson_1_class.qmd
        - section: "Autocorrelation"
          contents:
            - chapter_5/chapter_5_lesson_2_class.qmd
        - section: "Correlograms & Covariance of Sums"
          contents:
            - chapter_5/chapter_5_lesson_3_class.qmd

    - id: chapter_6
      title: "Chapter 6"
      style: "docked"
      collapse-level: 2
      contents:
        - section: "Expectation & Ensemble"
          contents:
            - chapter_6/chapter_6_lesson_1_class.qmd
        - section: "Autocorrelation"
          contents:
            - chapter_6/chapter_6_lesson_2_class.qmd
        - section: "Correlograms & Covariance of Sums"
          contents:
            - chapter_6/chapter_6_lesson_3_class.qmd

format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    toc: true

editor: visual


